title: DevOPS Project
description: This Project about DevOPS cources

# Development server config, needed to load some of the content
webrick:
  headers:
    Access-Control-Allow-Origin: "*"

# Theme settings
site_author: Andrey Mojseenko
repo_url: 'https://github.com/akitobora/Akinawa'
edit_on_github: true
github_docs_folder: false
sticky_navigation: true
prev_next_buttons_location: both
search_enabled: true
hljs_style: github-gist
